export const APP_NAME = "Anna's Artistic Store";
export const DOMAIN = 'https://anartist.turskyi.com';
export const DEVELOPER_DOMAIN = 'turskyi.com';
export const AUTHOR = 'Anna Turska';
export const INSTAGRAM = 'https://www.instagram.com/anartistdoll/';
export const FLICKR = 'https://www.flickr.com/photos/200341024@N05/';
export const RESEND_DOMAIN = 'kima.website';
export const MACOS_ZIP_URL = 'https://github.com/Turskyi/anartiststore/releases/download/1.0.7/anartiststore.zip';
export const TESTFLIGHT_URL = 'https://testflight.apple.com/join/CAWv7eC2';
